name: 'example'
description: 'Example app for the JsonDynamicWidget library'
publish_to: 'none'
version: '1.0.0+11'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: 'flutter'
  json_dynamic_widget: '^7.1.0+4'
  json_dynamic_widget_plugin_material_icons: 
    path: '../'
  json_theme: '^6.4.1'
  logging: '^1.2.0'
  material_icons_named: '^3.16.0'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'

flutter: 
  uses-material-design: true
  assets: 
    - 'assets/pages/'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
