name: json_dynamic_widget_plugin_material_icons
description: A plugin to the JSON Dynamic Widget to provide String name support for Material Icons
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_material_icons

version: 1.0.0+2

environment:
  sdk: ">=2.15.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  child_builder: ^2.0.0+2
  flutter:
    sdk: flutter
  json_class: ^2.1.2+3
  json_dynamic_widget: ^3.6.0+2
  json_theme: ^3.2.4
  logging: ^1.0.2
  material_icons_named: ^1.1.0+2
  meta: ^1.7.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
