name: 'json_dynamic_widget_plugin_material_icons'
description: 'A plugin to the JSON Dynamic Widget to provide String name support for Material Icons'
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget_plugin_material_icons'
version: '3.13.0+2'

environment: 
  sdk: '>=3.0.0 <4.0.0'

analyzer: 
  exclude: 
    - 'lib/generated/**'
    - 'lib/**/*.g.dart'


dependencies: 
  child_builder: '^2.0.1'
  flutter: 
    sdk: 'flutter'
  json_class: '^3.0.0+4'
  json_dynamic_widget: '^6.1.3+1'
  json_theme: '^6.2.5'
  logging: '^1.2.0'
  material_icons_named: '^3.13.0'
  meta: '^1.9.1'
  uuid: '^4.0.0'

false_secrets: 
  - 'example/web/index.html'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
